execute pathogen#infect()

let g:acp_enableAtStartup = 1
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1

inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

let g:racer_experimental_completer = 1

map <C-n> :NERDTreeToggle<CR>

set hidden
set number
set background=light
set expandtab
set tabstop=4
set shiftwidth=4
set nobackup
set ignorecase
set smarttab
set softtabstop=4
set wildmenu
set wildmode=longest:list
set modeline
set laststatus=2
set cc=79
set nolist
set linebreak
set formatoptions+=1
set hlsearch
set ruler
set showcmd
set incsearch
set nocompatible
set backspace=indent,eol,start
filetype plugin indent on
syntax on
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
