" mkdir -p ~/.vim/{autoload,bundle}
" cd ~/.vim/bundle
"
" git clone https://github.com/tpope/vim-pathogen
" ln -s ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim
"
" git clone https://github.com/tpope/vim-fugitive.git
" git clone --recursive https://github.com/davidhalter/jedi-vim.git
" git clone https://github.com/fatih/vim-go.git
" git clone https://github.com/scrooloose/nerdtree.git
" git clone https://github.com/ctrlpvim/ctrlp.vim
" git clone https://github.com/Valloric/YouCompleteMe
"
" cd YouCompleteMe
" ./install.py --clang-completer --system-libclang --go-completer --rust-completer
"
" Ready!

execute pathogen#infect()

let g:acp_enableAtStartup = 1

inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

let g:go_metalinter_autosave = 1
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
let g:go_fmt_command = "goimports"
let g:go_gocode_unimported_packages = 1
let g:go_template_use_pkg = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1

let g:racer_experimental_completer = 1

map <C-n> :NERDTreeToggle<CR>

set hidden
set number
set background=light
set expandtab
set tabstop=4
set shiftwidth=4
set nobackup
set ignorecase
set smarttab
set softtabstop=4
set wildmenu
set wildmode=longest:list
set modeline
set laststatus=2
set cc=79
set nolist
"set linebreak
set formatoptions+=1
set hlsearch
set ruler
set showcmd
set incsearch
set nocompatible
set backspace=indent,eol,start
filetype plugin indent on
syntax on
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
