" mkdir -p ~/.vim/{autoload,bundle}
" cd ~/.vim/bundle
"
" git clone https://github.com/tpope/vim-pathogen
" ln -s ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim
"
" git clone --recursive https://github.com/davidhalter/jedi-vim.git
" git clone --depth=1 https://github.com/rust-lang/rust.vim.git
" git clone git://github.com/airblade/vim-gitgutter.git
" git clone https://github.com/w0rp/ale
" git clone https://github.com/tpope/vim-fugitive.git
" git clone https://github.com/fatih/vim-go.git
" git clone https://github.com/scrooloose/nerdtree.git
" git clone https://github.com/junegunn/fzf.vim
" git clone https://github.com/Valloric/YouCompleteMe
"
" # First, install clang/libclang for the clang completer
"
" cd YouCompleteMe
" git submodule update --recursive --init
" ./install.py --clang-completer --system-libclang --go-completer --rust-completer
"
" Install the_silver_searcher then add in your ~/.${SHELL}rc:
"
" export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
"
" Ready!

execute pathogen#infect()

let g:acp_enableAtStartup = 1

inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"

" disable sign column if no error reported
set signcolumn=yes

let g:go_metalinter_autosave = 0
let g:go_metalinter_autosave_enabled = []
let g:go_fmt_command = "goimports"
let g:go_gocode_unimported_packages = 1
let g:go_template_use_pkg = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_list_type = "quickfix"

let g:racer_experimental_completer = 1

let g:ycm_min_num_of_chars_for_completion = 1
let g:ycm_max_num_candidates = 10
let g:ycm_complete_in_comments = 1

let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_open_list = 1
let g:ale_keep_list_window_open = 1
let g:ale_list_window_size = 4

let g:gitgutter_enabled = 1
let g:gitgutter_signs = 1

let g:fzf_buffers_jump = 1
let g:fzf_command_prefix = 'Fzf'

map <C-n> :NERDTreeToggle<CR>
map <C-p> :FzfFiles<CR>
map <C-b> :FzfBuffers<CR>

autocmd FileType go map <F2> :GoRename 
autocmd FileType go map <F3> :GoTestFunc<CR>
autocmd FileType go map <F4> :GoCoverageToggle<CR>

set hidden
set number
set background=dark
set expandtab
set tabstop=4
set shiftwidth=4
set nobackup
set ignorecase
set smarttab
set softtabstop=4
set wildmenu
set wildmode=longest:list
set modeline
set laststatus=2
set cc=79
set nolist
"set linebreak
set formatoptions+=1
set hlsearch
set ruler
set showcmd
set incsearch
set nocompatible
set backspace=indent,eol,start
filetype plugin indent on
syntax on
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
