#killall dbus-daemon
killall redshift
numlockx on
setxkbmap fr,fr,us bepo,, -option "xkb_options" "grp:alt_caps_toggle" -option caps:none
#export $(dbus-launch)
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
export _JAVA_AWT_WM_NONREPARENTING=1
#pulseaudio --start &
~/.screenlayout/home.sh
xset s off
xset -dpms
xset s noblank
/usr/lib/xfce4/notifyd/xfce4-notifyd &
redshift-gtk -l 48.85241:2.3488 -t 5500:3000 -r &
nitrogen --restore
parcellite &
nm-applet &
orage &
gnome-keyring-daemon -s -c pkcs11,secrets
#owncloud &
volumeicon &
usbguard-applet-qt &
akregator --hide-mainwindow &
#flameshot gui -p ~/Snapshots/ &
eval $(ssh-agent -s)
/usr/bin/i3
