killall dbus-daemon
killall redshift
export $(dbus-launch)
pulseaudio --start &
~/.screenlayout/home.sh
xset -dpms
/usr/lib/xfce4/notifyd/xfce4-notifyd &
redshift-gtk &
setxkbmap "fr,fr,us" "bepo,,"
nitrogen --restore
parcellite &
volumeicon &
nm-applet &
orage &
