/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
killall redshift
numlockx on
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
export _JAVA_AWT_WM_NONREPARENTING=1
~/.screenlayout/home.sh
xset s off
xset -dpms
xset s noblank
/usr/lib/xfce4/notifyd/xfce4-notifyd &
redshift-gtk -l 48.85241:2.3488 -t 5500:3000 -r &
nitrogen --restore
parcellite &
nm-applet &
orage &
# trizen -S gnome-keyring libsecret seahorse
eval $(gnome-keyring-daemon -s -c pkcs11,secrets)
#owncloud &
volumeicon &
usbguard-applet-qt &
#flameshot gui -p ~/Snapshots/ &
