" Prerequisites:
"
" system:
"   pacman -S base-devel clang cmake rust the_silver_searcher fzf npm nodejs
"   python-pylint python2-pylint python-jedi python2-jedi flake8
"   python2-flake8 autopep8 python2-autopep8 python-isort python2-isort go
"   python-virtualenv python2-virtualenv
"
" shell:
"   export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
"
" :GoInstallBinaries

set nocompatible
set encoding=utf-8
filetype off

" https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif

call plug#begin('~/.vim/plugged')

Plug 'rust-lang/rust.vim'
Plug 'airblade/vim-gitgutter'
Plug 'w0rp/ale'
Plug 'tpope/vim-fugitive'
Plug 'fatih/vim-go'
Plug 'scrooloose/nerdtree'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'Valloric/YouCompleteMe', {'dir': '~/.vim/plugged/YouCompleteMe', 'do': './install.py --clang-completer --system-libclang --go-completer --rust-completer --js-completer'}
Plug 'terryma/vim-multiple-cursors'
Plug 'aquach/vim-http-client'
Plug 'metakirby5/codi.vim'
Plug 'ntpeters/vim-better-whitespace'
Plug 'posva/vim-vue'
Plug 'fisadev/vim-isort'
Plug 'vimjas/vim-python-pep8-indent'

call plug#end()

let g:acp_enableAtStartup = 1

inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"

" disable sign column if no error reported
set signcolumn=yes

let g:go_metalinter_autosave = 0
let g:go_metalinter_autosave_enabled = []
let g:go_fmt_command = "goimports"
let g:go_gocode_unimported_packages = 1
let g:go_template_use_pkg = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_list_type = "quickfix"

let g:racer_experimental_completer = 1

let g:ycm_min_num_of_chars_for_completion = 3
let g:ycm_complete_in_comments = 0
let g:ycm_python_binary_path = 'python'
let g:ycm_autoclose_preview_window_after_insertion = 1

let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_open_list = 1
let g:ale_keep_list_window_open = 0
let g:ale_completion_enabled = 0
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
"let g:ale_list_window_size = 10

" use Ctrl+j to go through warning and errors
nmap <silent> <C-j> <Plug>(ale_next_wrap)

let g:gitgutter_enabled = 1
let g:gitgutter_signs = 1

let g:fzf_buffers_jump = 1
let g:fzf_command_prefix = 'Fzf'

map <C-n> :NERDTreeToggle<CR>
map <C-p> :FzfFiles<CR>
map <C-b> :FzfBuffers<CR>

autocmd FileType go map <F2> :GoRename 
autocmd FileType go map <F3> :GoTestFunc<CR>
autocmd FileType go map <F4> :GoCoverageToggle<CR>

set hidden
set number
set background=dark
set expandtab
set tabstop=4
set shiftwidth=4
set nobackup
set ignorecase
set smarttab
set softtabstop=4
set wildmenu
set wildmode=longest:list
set modeline
set laststatus=2
set cc=79
set nolist
"set linebreak
set formatoptions+=1
set hlsearch
set ruler
set showcmd
set incsearch
set backspace=indent,eol,start
filetype plugin indent on
syntax on
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
